// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://goxjoxqlyvsmyhrqmtlo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdveGpveHFseXZzbXlocnFtdGxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MDgzNDAsImV4cCI6MjA2OTQ4NDM0MH0.54WRum-iJzU1ew0EZBGa5BgCJKBsDZzKQpAPGuyd14I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});